FROM mageai/mageai:latest

ARG PROJECT_NAME=[demo_mage]
ARG MAGE_CODE_PATH=/home/mage_code
ARG USER_CODE_PATH=${MAGE_CODE_PATH}/${PROJECT_NAME}

WORKDIR ${MAGE_CODE_PATH}

COPY ${PROJECT_NAME} ${PROJECT_NAME}

ENV USER_CODE_PATH=${USER_CODE_PATH}

ENV PYTHONPATH="${PYTHONPATH}:/home/mage_code"
ENV REQUIRE_USER_AUTHENTICATION=1
ENV MAGE_ACCESS_TOKEN_EXPIRY_TIME=1440

CMD ["/bin/sh", "-c", "/app/run_app.sh"]
